name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  merge-pages:
    name: Merge to gh-pages branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'gh-pages'
          fetch-depth: 0
      - name: Git configuration
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "<41898282+github-actions[bot]@users.noreply.github.com>"
      - name: Merge to gh-pages
        run: |
          git merge origin/main
          git push
  deploy:
    name: Update github pages
    runs-on: ubuntu-latest
    needs: merge-pages
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'gh-pages'
          fetch-depth: 0
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.6'
          bundler-cache: true
      - name: add bundle stubs
        run: |
          bundle binstubs --all
      - run: PATH=bin:$PATH make build
        name: Build PDF & HTML
      - name: Copy files
        run: |
          mkdir -p docs
          cp -r out/* docs
      - name: Git configuration
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "<41898282+github-actions[bot]@users.noreply.github.com>"
      - name: Git Commit and Push
        run: |
          git add docs
          git diff-index --quiet HEAD || (git commit -m "Update github pages" && git push)
